### ISSUE TITLE
ensorflow_fold/loom/_deserializing_weaver_op.so: undefined symbol: 

### ISSUE THREAD

**Issue by SeekPoint** [ronghanghu/n2nmn#2]
mldl@mldlUB1604:~/ub16_prj/n2nmn$ 
mldl@mldlUB1604:~/ub16_prj/n2nmn$ python3 exp_clevr/train_clevr_gt_layout.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.68GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "exp_clevr/train_clevr_gt_layout.py", line 19, in <module>
    from models_clevr.nmn3_assembler import Assembler
  File "/home/mldl/ub16_prj/n2nmn/models_clevr/nmn3_assembler.py", line 5, in <module>
    import tensorflow_fold as td
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_fold/__init__.py", line 22, in <module>
    from tensorflow_fold.blocks.block_compiler import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_fold/blocks/block_compiler.py", line 28, in <module>
    from tensorflow_fold.blocks import loom_ops
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_fold/blocks/loom_ops.py", line 19, in <module>
    import tensorflow_fold.blocks.result_types as tdt
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_fold/blocks/result_types.py", line 27, in <module>
    from tensorflow_fold.public import loom
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_fold/public/loom.py", line 17, in <module>
    from tensorflow_fold.loom.loom import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_fold/loom/__init__.py", line 17, in <module>
    from tensorflow_fold.loom.loom import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_fold/loom/loom.py", line 36, in <module>
    from tensorflow_fold.loom import deserializing_weaver_op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_fold/loom/deserializing_weaver_op.py", line 34, in <module>
    tf.resource_loader.get_data_files_path(), '_deserializing_weaver_op.so'))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.5/dist-packages/tensorflow_fold/loom/_deserializing_weaver_op.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesESt16initializer_listINS_11StringPieceEE
mldl@mldlUB1604:~/ub16_prj/n2nmn$

**Comment by SeekPoint** [comment]
I got the solution
my tensorflow is 1.0.1,   it must be1.0.0 exactly!!!!
